
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieadbzgzsjxcafgzbysu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllYWRiemd6c2p4Y2FmZ3pieXN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NzczMzAsImV4cCI6MjA1NDM1MzMzMH0.XOk_V8U0nxEi-mQ6o5578cDM91_i-hcqENCVwUU026Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
